// AUTO-GENERATED by local-authority-silo-engine.
// Minimal silo catchall page. Brand-agnostic. Uses Tailwind + inline schema.
import Link from "next/link";
import { notFound } from "next/navigation";
import bundle from "@/lib/silo/content.json";
import { BRAND } from "@/lib/brand-constants";

type Params = { params: Promise<{ silo: string }> };

type SiloPage = {
  type: "city_hub" | "service_in_city" | "blog";
  url: string;
  title: string;
  meta_description: string;
  city: string;
  city_key: string;
  state_abbr: string;
  state: string;
  country?: string;
  lat?: number;
  lng?: number;
  intro?: string;
  local_context?: string;
  service_details?: string;
  service_slug?: string;
  service_label?: string;
  service_blurb?: string;
  authority_citations?: Array<{ name: string; url: string; context?: string }>;
  authority_citation?: { name: string; url: string; context?: string };
  faq?: Array<{ q: string; a: string }>;
  image: string;
  image_alt: string;
  neighborhoods?: string[];
  jurisdiction?: { body: string; statute: string; url: string };
  city_hub_url?: string;
  national_service_url?: string;
  legacy_hub_url?: string;
};

const ALL_PAGES = bundle.pages as SiloPage[];

// Deduplicate FLAT_PAGES: when a city_hub and service_in_city share the same URL,
// prefer service_in_city (city_hubs are placeholder stubs; service_in_city carries real content).
// This prevents 312 PM pages from rendering blank placeholder city_hub copy.
const FLAT_PAGES = (() => {
  const nonBlog = ALL_PAGES.filter((p) => p.type !== "blog");
  const seen = new Map<string, SiloPage>();
  for (const p of nonBlog) {
    const existing = seen.get(p.url);
    if (!existing) {
      seen.set(p.url, p);
    } else if (existing.type === "city_hub" && p.type === "service_in_city") {
      // service_in_city wins over placeholder city_hub
      seen.set(p.url, p);
    }
  }
  return Array.from(seen.values());
})();

export const dynamic = "force-static";
export const dynamicParams = false;

export async function generateStaticParams() {
  return FLAT_PAGES.map((p) => ({ silo: p.url.replace(/^\//, "") }));
}

// Meta descriptions in the content bundle are sometimes truncated mid-sentence at ~130 chars.
// This helper returns a clean description that ends at a sentence boundary or adds a proper suffix.
function cleanMetaDescription(page: SiloPage): string {
  const raw = page.meta_description || "";
  // If it ends cleanly at sentence punctuation, use as-is
  if (raw.match(/[.!?]$/)) return raw;
  // If truncated mid-sentence, build a clean fallback from the pattern we know:
  // "{Brand} {Service} in {City}, {State}. {service_blurb}."
  if (page.service_label && page.city && page.state_abbr) {
    const blurb = page.service_blurb
      ? page.service_blurb.replace(/\.$/, "") + "."
      : `Professional ${page.service_label.toLowerCase()} services in ${page.city}, ${page.state_abbr}.`;
    return `${BRAND.name} ${page.service_label} in ${page.city}, ${page.state_abbr}. ${blurb}`;
  }
  // City hub fallback
  if (page.city && page.state_abbr) {
    return `${BRAND.name} property management and leasing services in ${page.city}, ${page.state_abbr}. Full-service North American coverage.`;
  }
  return raw;
}

export async function generateMetadata({ params }: Params) {
  const { silo } = await params;
  const page = FLAT_PAGES.find((p) => p.url === `/${silo}`);
  if (!page) return {};
  const description = cleanMetaDescription(page);
  return {
    title: `${page.title} | ${BRAND.name}`,
    description,
    alternates: { canonical: `${BRAND.url}${page.url}` },
    openGraph: {
      title: page.title,
      description,
      url: `${BRAND.url}${page.url}`,
      siteName: BRAND.name,
      type: "website",
    },
  };
}

function buildSchema(page: SiloPage) {
  const graph: Record<string, unknown>[] = [
    {
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: BRAND.url },
        { "@type": "ListItem", position: 2, name: page.title, item: `${BRAND.url}${page.url}` },
      ],
    },
  ];

  if (page.type === "city_hub") {
    graph.push({
      "@type": "LocalBusiness",
      "@id": `${BRAND.url}${page.url}#localbusiness`,
      name: `${BRAND.name} - ${page.city}, ${page.state_abbr}`,
      url: `${BRAND.url}${page.url}`,
      telephone: BRAND.phone,
      areaServed: {
        "@type": "City",
        name: page.city,
        containedInPlace: { "@type": "State", name: page.state },
      },
      ...(page.lat && page.lng
        ? {
            geo: {
              "@type": "GeoCoordinates",
              latitude: page.lat,
              longitude: page.lng,
            },
          }
        : {}),
    });
  } else if (page.type === "service_in_city") {
    graph.push({
      "@type": "Service",
      "@id": `${BRAND.url}${page.url}#service`,
      name: `${page.service_label} in ${page.city}, ${page.state_abbr}`,
      provider: { "@type": "LocalBusiness", name: BRAND.name, url: BRAND.url },
      areaServed: { "@type": "City", name: page.city },
      description: page.service_blurb,
    });
  }

  if (page.faq && page.faq.length > 0) {
    graph.push({
      "@type": "FAQPage",
      mainEntity: page.faq.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    });
  }

  return { "@context": "https://schema.org", "@graph": graph };
}

export default async function SiloFlatPage({ params }: Params) {
  const { silo } = await params;
  const page = FLAT_PAGES.find((p) => p.url === `/${silo}`);
  if (!page) notFound();

  const cityPages = ALL_PAGES.filter((p) => p.city_key === page.city_key);
  const siblingServices = cityPages.filter(
    (p) => p.type === "service_in_city" && p.url !== page.url
  );
  const cityHub = cityPages.find((p) => p.type === "city_hub");
  const cityBlogs = cityPages.filter((p) => p.type === "blog");

  return (
    <>
      <script
        type="application/ld+json"
        suppressHydrationWarning
        dangerouslySetInnerHTML={{ __html: JSON.stringify(buildSchema(page)) }}
      />

      <section className="bg-white border-b border-neutral-200">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <nav className="text-sm text-neutral-500 mb-3">
            <Link href="/" className="hover:underline">
              Home
            </Link>
            {" / "}
            {cityHub && cityHub.url !== page.url ? (
              <>
                <Link href={cityHub.url} className="hover:underline">
                  {page.city}
                </Link>
                {page.type === "service_in_city" && (
                  <span> / {page.service_label}</span>
                )}
              </>
            ) : (
              <span>{page.city}</span>
            )}
          </nav>
          <p className="text-xs uppercase tracking-wider text-neutral-500 mb-2">
            {page.type === "city_hub" ? "City coverage" : "Service coverage"}
          </p>
          <h1 className="text-3xl md:text-4xl font-semibold text-neutral-900">
            {page.title}
          </h1>
          <p className="mt-3 text-neutral-700 max-w-3xl">
            {page.meta_description}
          </p>
          <div className="mt-6 flex flex-col sm:flex-row gap-3">
            <a
              href={`tel:${BRAND.phone}`}
              className="inline-flex items-center justify-center rounded-md bg-neutral-900 text-white px-5 py-3 text-sm font-medium hover:bg-neutral-800"
            >
              Call {BRAND.phoneDisplay}
            </a>
            <Link
              href="/contact"
              className="inline-flex items-center justify-center rounded-md border border-neutral-300 px-5 py-3 text-sm font-medium hover:border-neutral-900"
            >
              Request leasing service
            </Link>
          </div>
        </div>
      </section>

      <section className="bg-white">
        <div className="mx-auto max-w-3xl px-6 py-12 prose prose-neutral">
          {page.intro && <p>{page.intro}</p>}
          {page.local_context && <p>{page.local_context}</p>}
          {page.service_details && <p>{page.service_details}</p>}
        </div>
      </section>

      {(page.authority_citations || page.authority_citation) && (
        <section className="bg-neutral-50 border-t border-neutral-200">
          <div className="mx-auto max-w-3xl px-6 py-10">
            <p className="text-xs uppercase tracking-wider text-neutral-500 mb-3">
              Local authority sources
            </p>
            <h2 className="text-xl font-semibold text-neutral-900 mb-4">
              Cited references for this market.
            </h2>
            <ul className="space-y-3">
              {((page.authority_citations || []).concat(
                page.authority_citation ? [page.authority_citation] : []
              ) as Array<{ name: string; url: string; context?: string }>).map(
                (a, i) =>
                  a && a.url ? (
                    <li key={i}>
                      <a
                        href={a.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="font-semibold text-neutral-900 underline"
                      >
                        {a.name}
                      </a>
                      {a.context && (
                        <p className="text-sm text-neutral-600 mt-1">{a.context}</p>
                      )}
                    </li>
                  ) : null
              )}
            </ul>
          </div>
        </section>
      )}

      {page.type === "city_hub" && page.legacy_hub_url && (
        <section className="bg-white border-t border-neutral-200">
          <div className="mx-auto max-w-6xl px-6 py-4 text-sm">
            <Link
              href={page.legacy_hub_url}
              className="text-neutral-700 underline hover:text-neutral-900"
            >
              See the original {page.city} hub
            </Link>
          </div>
        </section>
      )}

      {page.type === "city_hub" && siblingServices.length > 0 && (
        <section className="bg-white border-t border-neutral-200">
          <div className="mx-auto max-w-6xl px-6 py-12">
            <p className="text-xs uppercase tracking-wider text-neutral-500 mb-3">
              Service lines in this city
            </p>
            <h2 className="text-xl font-semibold text-neutral-900 mb-6">
              What we run in {page.city}.
            </h2>
            <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {siblingServices.map((s) => (
                <li key={s.url}>
                  <Link
                    href={s.url}
                    className="block rounded-lg border border-neutral-200 bg-white p-5 hover:border-neutral-900 transition"
                  >
                    <p className="font-semibold text-neutral-900">
                      {s.service_label}
                    </p>
                    <p className="text-sm text-neutral-600 mt-1">
                      {s.service_blurb}
                    </p>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>
      )}

      {page.type === "service_in_city" && (
        <section className="bg-white border-t border-neutral-200">
          <div className="mx-auto max-w-6xl px-6 py-12 grid grid-cols-1 lg:grid-cols-3 gap-6">
            {cityHub && (
              <Link
                href={cityHub.url}
                className="rounded-lg border border-neutral-200 bg-neutral-50 p-5 hover:border-neutral-900 transition"
              >
                <p className="text-xs uppercase tracking-wider text-neutral-500 mb-2">
                  City hub
                </p>
                <p className="font-semibold text-neutral-900">{cityHub.title}</p>
              </Link>
            )}
            {page.national_service_url && (
              <Link
                href={page.national_service_url}
                className="rounded-lg border border-neutral-200 bg-white p-5 hover:border-neutral-900 transition"
              >
                <p className="text-xs uppercase tracking-wider text-neutral-500 mb-2">
                  National service line
                </p>
                <p className="font-semibold text-neutral-900">{page.service_label}</p>
              </Link>
            )}
            {siblingServices.slice(0, 1).map((s) => (
              <Link
                key={s.url}
                href={s.url}
                className="rounded-lg border border-neutral-200 bg-white p-5 hover:border-neutral-900 transition"
              >
                <p className="text-xs uppercase tracking-wider text-neutral-500 mb-2">
                  Related in {page.city}
                </p>
                <p className="font-semibold text-neutral-900">{s.service_label}</p>
              </Link>
            ))}
          </div>
        </section>
      )}

      {page.faq && page.faq.length > 0 && (
        <section className="bg-neutral-50 border-t border-neutral-200">
          <div className="mx-auto max-w-3xl px-6 py-12">
            <p className="text-xs uppercase tracking-wider text-neutral-500 mb-3">
              FAQ
            </p>
            <h2 className="text-xl font-semibold text-neutral-900 mb-6">
              Common questions.
            </h2>
            <div className="space-y-4">
              {page.faq.map((f, i) => (
                <details
                  key={i}
                  className="rounded-lg border border-neutral-200 bg-white p-5"
                >
                  <summary className="font-semibold text-neutral-900 cursor-pointer">
                    {f.q}
                  </summary>
                  <p className="mt-3 text-neutral-700">{f.a}</p>
                </details>
              ))}
            </div>
          </div>
        </section>
      )}

      {cityBlogs.length > 0 && (
        <section className="bg-white border-t border-neutral-200">
          <div className="mx-auto max-w-6xl px-6 py-12">
            <p className="text-xs uppercase tracking-wider text-neutral-500 mb-3">
              Local guides
            </p>
            <h2 className="text-xl font-semibold text-neutral-900 mb-6">
              More from {page.city}.
            </h2>
            <ul className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {cityBlogs.map((b) => (
                <li key={b.url}>
                  <Link
                    href={b.url}
                    className="block rounded-lg border border-neutral-200 bg-white p-5 hover:border-neutral-900 transition"
                  >
                    <p className="font-semibold text-neutral-900">{b.title}</p>
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </section>
      )}
    </>
  );
}
